# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c8a8b10fc3ce477bef4f77ceed301a7fe98f1f4a8363cbd2968df04f882f404aa75a116735a5a60ac40a207cd583a6bcaea5d253c7eb3c8087931b51705721

test:
  secret_key_base: ce11f536244c02398d0d5c6b56ee7cd9eccd7cf2fd8c3c90d7c7391da7d9a5f5c4e9d6319120659a06ae929d7637fa47c04c62edcea5fdf1e1baf5f7185c8181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
